import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import prettierConfig from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      'node_modules/',
      '.cache/',
      'public/',
      'coverage/',
      'src/gatsby-types.d.ts', // generated by gatsby's graphql typegen
    ],
  },

  // Applies to every config below that inspects React; without it
  // eslint-plugin-react warns on every run.
  { settings: { react: { version: 'detect' } } },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  react.configs.flat.recommended,
  react.configs.flat['jsx-runtime'],

  // jsx-a11y's recommended preset reports at `error` severity. Combined with
  // `--max-warnings=0` in CI, an accessibility violation fails the build exactly
  // like a type error. That is deliberate: warnings get ignored, errors do not.
  jsxA11y.flatConfigs.recommended,

  {
    files: ['**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    settings: { react: { version: 'detect' } },
    rules: {
      ...reactHooks.configs.recommended.rules,

      // TypeScript already validates props; prop-types would duplicate it.
      'react/prop-types': 'off',

      // `any` disables type checking silently. Where a value is genuinely
      // unknown, `unknown` forces a narrowing check at the point of use.
      '@typescript-eslint/no-explicit-any': 'error',

      // `_`-prefixed values are intentionally unused (e.g. omitted destructured
      // props); everything else is dead code.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],

      // Keeps type-only imports erasable at compile time, which matters under
      // `isolatedModules` and avoids accidental runtime imports of type modules.
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],

      // Errors must surface. console.error/warn stay available for genuine
      // failures; stray console.log is debugging residue.
      'no-console': ['error', { allow: ['warn', 'error'] }],
    },
  },

  {
    // Build tooling that must stay CommonJS (jest.config.js, jest.preprocess.js).
    // Declaring the few Node globals used avoids adding the `globals` package.
    files: ['**/*.js'],
    languageOptions: {
      globals: { module: 'writable', require: 'readonly', __dirname: 'readonly' },
    },
    rules: {
      // These files must remain CommonJS: jest loads them before any ESM
      // transform is available.
      '@typescript-eslint/no-require-imports': 'off',
    },
  },

  // Must be last: disables stylistic rules that would conflict with Prettier.
  prettierConfig,
);
